"""
Collett - Icon Theme Utils
==========================

This file is a part of Collett
Copyright (C) 2026 Veronica Berglyd Olsen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""  # noqa

from __future__ import annotations

import argparse
import shutil
import urllib.request
import zipfile

from pathlib import Path
from xml.etree import ElementTree as ET

from utils.common import ROOT_DIR, log, readEnvFile

ET.register_namespace("", "http://www.w3.org/2000/svg")

# Source: https://lucide.dev/
ICON_SOURCE = "https://github.com/lucide-icons/lucide/archive/refs/tags/1.51.0.zip"
ICON_EXTRACT = "lucide-1.51.0"

# fmt: off
ICONS = {
    # Classes
    "cls_archive": "archive",
    "cls_character": "users",
    "cls_custom": "star",
    "cls_entity": "university",
    "cls_location": "map-pin",
    "cls_novel": "book",
    "cls_object": "hammer",
    "cls_plot": "hat-glasses",
    "cls_trash": "trash",

    # Formatting
    "fmt_bold": "bold",
    "fmt_italic": "italic",
    "fmt_strike": "strikethrough",
    "fmt_subscript": "subscript",
    "fmt_superscript": "superscript",
    "fmt_underline": "underline",
    "fmt_align_left": "text-align-start",
    "fmt_align_center": "text-align-center",
    "fmt_align_right": "text-align-end",
    "fmt_align_justify": "text-align-justify",
    "fmt_indent": "list-indent-increase",
    "fmt_outdent": "list-indent-decrease",

    # Project
    "prj_chapter": "file-text",
    "prj_document": "file-text",
    "prj_folder": "folder",
    "prj_note": "file-check",
    "prj_scene": "file-text",
    "prj_title": "file-text",

    # Menu
    "menu_project": "bookmark",

    # Buttons
    "btn_cancel": "circle-slash",
    "btn_ok": "circle-check-big",
    "btn_save": "save",

    # Arrows
    "arrow_down": "chevron-down",
    "arrow_left": "chevron-left",
    "arrow_right": "chevron-right",
    "arrow_up": "chevron-up",

    # Actions
    "add": "plus",
    "bookmarks": "bookmark",
    "checked": "circle-check-big",
    "font": "type",
    "noncheckable": "circle",
    "settings": "settings",
    "theme_auto": "contrast",
    "theme_dark": "moon",
    "theme_light": "sun",
    "unchecked": "circle-x",
}
# fmt: on


def _writeThemeFile(path: Path, name: str, author: str, license_: str, icons: dict[str, ET.Element]) -> None:
    """Write an icon theme file, with each icon's SVG on a single line."""
    width = max(len(k) for k in icons)
    with open(path, mode="w", encoding="utf-8") as out:
        out.write("# This file is automatically generated. Do not edit.\n\n")
        out.write("# Meta\n")
        out.write(f"meta:name    = {name}\n")
        out.write(f"meta:author  = {author}\n")
        out.write(f"meta:license = {license_}\n")
        out.write("\n")
        out.write("# Icons\n")
        for key, svg in icons.items():
            ET.indent(svg, space="")
            icon = ET.tostring(svg).decode().replace("\n", "")
            out.write(f"icon:{key:<{width}s} = {icon}\n")
    log(f"- [cg]Wrote:[e] {len(icons)} icons")
    log(f"- Target: {path.relative_to(ROOT_DIR)}")


def _downloadIconPack(workDir: Path) -> None:
    """Download and extract the Lucide icon pack release."""
    log(f"[b]Downloading:[e] {ICON_SOURCE}")
    zipFile = workDir / "lucide.zip"
    urllib.request.urlretrieve(ICON_SOURCE, zipFile)
    log(f"[b]Extracting:[e] {zipFile.name}")
    with zipfile.ZipFile(zipFile, "r") as inFile:
        inFile.extractall(workDir)
    log("")


def processLucide(workDir: Path, iconsDir: Path) -> None:
    """Process Lucide icons and write the theme and licence files."""
    srcRepo = workDir / ICON_EXTRACT
    if not srcRepo.is_dir():
        _downloadIconPack(workDir)

    log("[b]Processing:[e] Lucide")

    icons: dict[str, ET.Element] = {}
    iconSrc = srcRepo / "icons"
    for key, icon in ICONS.items():
        iconFile = iconSrc / f"{icon}.svg"
        if iconFile.is_file():
            icons[key] = ET.fromstring(iconFile.read_text(encoding="utf-8"))
        else:
            log(f"[cr]Not Found:[e] {iconFile}")

    _writeThemeFile(iconsDir / "lucide.icons", "Lucide", "Cole Bemis, Lucide Contributors", "ISC/MIT License", icons)
    shutil.copyfile(srcRepo / "LICENSE", iconsDir / "lucide.license")
    log("")


def main(args: argparse.Namespace) -> None:
    """Build icon themes entry point."""
    log("")
    log("[b]Build Icon Themes[e]")
    log("[b]=================[e]")

    if args.work_dir:
        workDir = Path(args.work_dir).absolute()
    elif cacheDir := readEnvFile().get("CACHE_DIR"):
        workDir = Path(cacheDir).expanduser().absolute() / "icons"
    else:
        workDir = ROOT_DIR / "build_icons"

    workDir.mkdir(parents=True, exist_ok=True)

    log(f"Work Dir: {workDir}")
    log("")

    iconsDir = ROOT_DIR / "assets" / "icons"
    iconsDir.mkdir(parents=True, exist_ok=True)
    processLucide(workDir, iconsDir)

    log("[cg]Done[e]")
    log("")
