"""
Collett - Icon Theme Utils
==========================

This file is a part of Collett
Copyright (C) 2026 Veronica Berglyd Olsen

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
"""

from __future__ import annotations

import urllib.request
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ET.register_namespace("", "http://www.w3.org/2000/svg")
ROOT_DIR = Path(__file__).parent.parent

ICON_SOURCE = "https://github.com/lucide-icons/lucide/archive/refs/tags/1.24.0.zip"
ICON_EXTRACT = "lucide-1.24.0"

ICONS = {
    #
    # Classes
    #
    "cls_archive": "archive",
    "cls_character": "users",
    "cls_custom": "star",
    "cls_entity": "university",
    "cls_location": "map-pin",
    "cls_novel": "book",
    "cls_object": "hammer",
    "cls_plot": "hat-glasses",
    "cls_trash": "trash-2",
    #
    # Formatting
    #
    "fmt_bold": "bold",
    "fmt_italic": "italic",
    "fmt_strike": "strikethrough",
    "fmt_subscript": "subscript",
    "fmt_superscript": "superscript",
    "fmt_underline": "underline",
    "fmt_align_left": "text-align-start",
    "fmt_align_center": "text-align-center",
    "fmt_align_right": "text-align-end",
    "fmt_align_justify": "text-align-justify",
    "fmt_indent": "list-indent-increase",
    "fmt_outdent": "list-indent-decrease",
    #
    # Project
    #
    "prj_chapter": "file-text",
    "prj_document": "file-text",
    "prj_folder": "folder",
    "prj_note": "file-check",
    "prj_scene": "file-text",
    "prj_title": "file-text",
    #
    # Menu
    #
    "menu_project": "book-marked",
    #
    # Actions
    #
    "add": "plus",
    "bookmarks": "bookmark",
    "checked": "circle-check-big",
    "noncheckable": "circle",
    "unchecked": "circle-x",
}


def _fixXml(svg: ET.Element) -> str:
    """Clean up the SVG XML and add needed fields."""
    svg.set("fill", "none")
    svg.set("stroke", "#000000")
    svg.set("height", "128")
    svg.set("width", "128")
    return ET.tostring(svg).decode().replace("\n", "")


def _writeThemeFile(path: Path, name: str, author: str, license: str, icons: dict[str, ET.Element]) -> None:
    """Write an icon theme file."""
    width = max(len(k) for k in ICONS)
    padding = " " * width
    with open(path.with_suffix(".icons"), mode="w", encoding="utf-8") as out:
        out.write("# This file is automatically generated. Do not edit.\n\n")
        out.write("# Meta\n")
        out.write(f"meta:name    = {name}\n")
        out.write(f"meta:author  = {author}\n")
        out.write(f"meta:license = {license}\n")
        out.write("\n")
        out.write("# Icons\n")
        for key, svg in icons.items():
            padded = f"{key}{padding}"[:width]
            out.write(f"icon:{padded} = {_fixXml(svg)}\n")
        print(f"- Wrote: {len(icons)} icons")
        print(f"- Target: {path.relative_to(ROOT_DIR)}")


def _downloadIconPack(workDir: Path) -> Path:
    """Download and extract the Lucide icon pack release."""
    print(f"Downloading: {ICON_SOURCE}")
    zipFile = workDir / "lucide.zip"
    urllib.request.urlretrieve(ICON_SOURCE, zipFile)
    print(f"Extracting: {zipFile.name}")
    with zipfile.ZipFile(zipFile, "r") as inFile:
        inFile.extractall(workDir)
    print()
    return workDir / ICON_EXTRACT


def processLucide(workDir: Path, iconsDir: Path) -> None:
    """Process Lucide icons and write the output file."""
    srcRepo = workDir / ICON_EXTRACT
    if not srcRepo.is_dir():
        srcRepo = _downloadIconPack(workDir)

    print("Processing: Lucide")

    icons: dict[str, ET.Element] = {}
    iconSrc = srcRepo / "icons"
    for key, icon in ICONS.items():
        iconFile = iconSrc / f"{icon}.svg"
        if iconFile.is_file():
            icons[key] = ET.fromstring(iconFile.read_text(encoding="utf-8"))
        else:
            print(f"Not Found: {iconFile}")

    target = iconsDir / "lucide.icons"
    _writeThemeFile(target, "Lucide", "Cole Bemis, Lucide Contributors", "ISC/MIT License", icons)

    print()


def main() -> None:
    """Build icon themes entry point."""
    print()
    print("Build Icon Themes")
    print("=================")
    print()

    workDir = ROOT_DIR / "_temp"
    workDir.mkdir(parents=True, exist_ok=True)

    outDir = ROOT_DIR / "assets" / "icons"
    outDir.mkdir(exist_ok=True)
    processLucide(workDir, outDir)

    print("Done")
    print()


if __name__ == "__main__":
    """Parse command line options and run the commands."""
    main()
